### ISSUE TITLE
Add attribute filtering in results of search

### ISSUE THREAD

**Issue by radmilak** [elixir-oslo/trackfind#152]
It is problematic for the HB client to store a lot of data and only cca 10 fields from the fairtracks JSON/GSuite are used in the ProTo frontend. It would be very useful to be able to pass a list of attributes to the search call and only these would be then returned in the JSON that is sent to JsonToGsuite api, making the resulting GSuite much smaller as well.

**Comment by dtitov** [comment]
So, if it will be a new parameter to the search query called `attributes`, where attributes are coma-separated (e.g. `...&attributes=samples.content->'donor_age',samples.content->'phenotype'->'term_label'`), could you, please, provide a list that would actually work? I'm trying on my own, but conversion always fails since GSuite seems to require some attributes to be present...

**Comment by dtitov** [comment]
So, if it will be a new parameter to the search query called `attributes`, where attributes are coma-separated (e.g. `...&attributes=samples.content->'donor_age',samples.content->'phenotype'->'term_label'`), could you, please, provide a list that would actually work? I'm trying on my own, but conversion always fails since GSuite seems to require some attributes to be present...

**Comment by radmilak** [comment]
So the required attributes for the GSuite api are these: tracks->file_url, tracks->label_short and tracks->assembly_name Sorry, I forgot about these a bit and you were very fast :-D.  The question is on which side should we 'require' these - should I make sure to always send them in the request or will you add them on your side?

**Comment by dtitov** [comment]
Thanks. I think we should assume that those 3 are always coming from you, because generally, it's the rest-GSuite service that knows which attributes are mandatory for it, and I wouldn't duplicate this knowledge to the TrackFind too: separation of responsibilities. Anyway, I'll proceed now.

**Comment by dtitov** [comment]
Ok, I've added it. Here's the way to test:

Without filtering: https://trackfind-dev.gtrack.no/api/v1/search/Example/Example?query=experiments.content->'global_id' ? 'geo:GSE35583'

With filtering: https://trackfind-dev.gtrack.no/api/v1/search/Example/Example?attributes=tracks.content->'file_url',tracks.content->'label_short',tracks.content->'assembly_name'&query=experiments.content->'global_id' ? 'geo:GSE35583'

Could you, please, test it too and let me know if anything is wrong?
